openapi: 3.0.1
info:
  contact:
    name: Precisely APIs Support
    url: https://support.precisely.com
  description: '

    Demographics. Audience Enrichment. Add local demographics and lifestyle

    segmentation to your audience profiles. The Demographics API returns

    household demographics and lifestyle characteristics with the input of an

    address, location coordinate, or geographic boundary. This service covers

    select countries.'
  license:
    name: Apache 2.0
    url: http://springdoc.org
  termsOfService: http://swagger.io/terms/
  title: Precisely APIs School API
  version: 18.1.0
servers:
- url: https://api.precisely.com
security:
- oAuth2Password:
  - ''
tags:
- name: School
paths:
  /schools/v1/school/byaddress:
    get:
      description: Search Nearby Schools by Address
      operationId: getSchoolsByAddress
      parameters:
      - description: free form address text
        in: query
        name: address
        required: true
        schema:
          type: string
      - description: 'Single digit code for education level applicable values are P -> primary, M -> Middle, H -> High, O -> Mixed Grades for public school type andE -> Elementary , S -> Secondary , O -> Others mixed grades for private schools '
        in: query
        name: edLevel
        required: false
        schema:
          type: string
      - description: Single digit code for schoolTypes applicable values are PRI and PUB
        in: query
        name: schoolType
        required: false
        schema:
          type: string
      - description: Single digit code for schoolSubType Applicable values are C, M, A, R, I, L, P, V, U, S (i.e. Charter, Magnet, Alternative, Regular, Indian, Military, Reportable Program, Vocational, Unknown, Special Education)
        in: query
        name: schoolSubType
        required: false
        schema:
          type: string
      - description: Single digit code for gender Applicable values are C, F, M (Coed, All Females, All Males) Applicable for Private Schools Only
        in: query
        name: gender
        required: false
        schema:
          type: string
      - description: 'Single digit code for assignedSchoolOnly applicable values are  Y/N '
        in: query
        name: assignedSchoolsOnly
        required: false
        schema:
          type: string
      - description: 'Single digit code for districtSchoolOnly applicable values are Y/N '
        in: query
        name: districtSchoolsOnly
        required: false
        schema:
          type: string
      - description: Search Radius within which schools are searched
        in: query
        name: searchRadius
        required: false
        schema:
          type: string
      - description: Search Radius unit applicable values are feet,kilometers,miles,meters
        in: query
        name: searchRadiusUnit
        required: false
        schema:
          type: string
      - description: Travel Time based on travelMode within which schools are searched.
        in: query
        name: travelTime
        required: false
        schema:
          type: string
      - description: 'Travel Time unit applicable values are minutes,hours,seconds,milliseconds '
        in: query
        name: travelTimeUnit
        required: false
        schema:
          type: string
      - description: Travel Distance based on travelMode within which schools are searched.
        in: query
        name: travelDistance
        required: false
        schema:
          type: string
      - description: Travel distanceUnit applicable values are feet,kilometers,miles,meters
        in: query
        name: travelDistanceUnit
        required: false
        schema:
          type: string
      - description: Travel mode Required when travelDistance or travelTime is specified. Accepted values are walking,driving
        in: query
        name: travelMode
        required: false
        schema:
          type: string
      - description: 'Max result to search '
        in: query
        name: maxCandidates
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchoolsNearByResponse'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInfo_1'
          description: Bad Request
        '500':
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
      security:
      - oAuth2Password: []
      summary: Search Nearby Schools by Address
      tags:
      - School
      x-accepts: application/json
components:
  schemas:
    SchoolRanking:
      example:
        avgMathScore: avgMathScore
        current: current
        statePercentileScore: statePercentileScore
        stateRank: stateRank
        numberOfSchools: numberOfSchools
        avgReadingScore: avgReadingScore
        rankYear: rankYear
      properties:
        current:
          type: string
        rankYear:
          type: string
        stateRank:
          type: string
        numberOfSchools:
          type: string
        avgMathScore:
          type: string
        avgReadingScore:
          type: string
        statePercentileScore:
          type: string
      type: object
    SchoolProfile:
      example:
        titleI: titleI
        freeOrReducedPriceLunches:
          reducedPriceLunchedCount: reducedPriceLunchedCount
          freeLunchesCount: freeLunchesCount
          totalCount: totalCount
        studentBelowPovertyPct: studentBelowPovertyPct
        advancePlacementClasses: advancePlacementClasses
        internationalBaccalaureate: internationalBaccalaureate
        studentEthnicity:
          twoOrMoreRaces: twoOrMoreRaces
          hawaiianPacificlslander: hawaiianPacificlslander
          white: white
          asian: asian
          hispanic: hispanic
          black: black
          indianAlaskaNative: indianAlaskaNative
        blueRibbon: blueRibbon
        expensePerStudent: expensePerStudent
      properties:
        blueRibbon:
          type: string
        internationalBaccalaureate:
          type: string
        titleI:
          type: string
        expensePerStudent:
          type: string
        studentBelowPovertyPct:
          type: string
        advancePlacementClasses:
          type: string
        freeOrReducedPriceLunches:
          $ref: '#/components/schemas/FreeOrReducedPriceLunches'
        studentEthnicity:
          $ref: '#/components/schemas/StudentEthnicity'
      type: object
    FreeOrReducedPriceLunches:
      example:
        reducedPriceLunchedCount: reducedPriceLunchedCount
        freeLunchesCount: freeLunchesCount
        totalCount: totalCount
      properties:
        freeLunchesCount:
          type: string
        reducedPriceLunchedCount:
          type: string
        totalCount:
          type: string
      type: object
    GradeLevelsTaught:
      example:
        tenth: tenth
        eighth: eighth
        eleventh: eleventh
        second: second
        sixth: sixth
        third: third
        seventh: seventh
        twelfth: twelfth
        ninth: ninth
        fifth: fifth
        pk: pk
        fourth: fourth
        kg: kg
        first: first
      properties:
        pk:
          type: string
        kg:
          type: string
        first:
          type: string
        second:
          type: string
        third:
          type: string
        fourth:
          type: string
        fifth:
          type: string
        sixth:
          type: string
        seventh:
          type: string
        eighth:
          type: string
        ninth:
          type: string
        tenth:
          type: string
        eleventh:
          type: string
        twelfth:
          type: string
      type: object
    address_1:
      example:
        country: country
        streetSide: streetSide
        city: city
        displayName: displayName
        postalCode: postalCode
        latitude: latitude
        businessName: businessName
        county: county
        unitType: unitType
        streetName: streetName
        formattedAddress: formattedAddress
        addressLine1: addressLine1
        mainAddressLine: mainAddressLine
        addressLine2: addressLine2
        addressLine3: addressLine3
        objectId: objectId
        addressLastLine: addressLastLine
        longitude: longitude
        unitValue: unitValue
        stateProvince: stateProvince
        urbanizationName: urbanizationName
        areaName1: areaName1
        areaName2: areaName2
        areaName3: areaName3
        areaName4: areaName4
        addressNumber: addressNumber
        postCode: postCode
        postCodeExt: postCodeExt
        placeName: placeName
        status: status
      properties:
        objectId:
          type: string
        displayName:
          type: string
        streetSide:
          type: string
        businessName:
          type: string
        addressLine1:
          type: string
        addressLine2:
          type: string
        addressLine3:
          type: string
        city:
          type: string
        stateProvince:
          type: string
        county:
          type: string
        postalCode:
          type: string
        latitude:
          type: string
        longitude:
          type: string
        status:
          type: string
        urbanizationName:
          type: string
        formattedAddress:
          type: string
        mainAddressLine:
          type: string
        addressLastLine:
          type: string
        placeName:
          type: string
        areaName1:
          type: string
        areaName2:
          type: string
        areaName3:
          type: string
        areaName4:
          type: string
        postCode:
          type: string
        postCodeExt:
          type: string
        country:
          type: string
        addressNumber:
          type: string
        streetName:
          type: string
        unitType:
          type: string
        unitValue:
          type: string
      type: object
    distance:
      example:
        unit: unit
        value: value
      properties:
        unit:
          type: string
        value:
          type: string
      type: object
    School:
      example:
        schoolSubTypeDesc: schoolSubTypeDesc
        gender: gender
        distance:
          unit: unit
          value: value
        schoolType: schoolType
        coextensiv: coextensiv
        students: students
        schoolDistricts:
          totalSchools: totalSchools
          metro: metro
          districtUrl: districtUrl
          name: name
          districtType: districtType
          supervisoryUnionId: supervisoryUnionId
          areaInSqM: areaInSqM
          ncesDistrictId: ncesDistrictId
          districtEnrollment: districtEnrollment
        genderDesc: genderDesc
        schoolProfile:
          titleI: titleI
          freeOrReducedPriceLunches:
            reducedPriceLunchedCount: reducedPriceLunchedCount
            freeLunchesCount: freeLunchesCount
            totalCount: totalCount
          studentBelowPovertyPct: studentBelowPovertyPct
          advancePlacementClasses: advancePlacementClasses
          internationalBaccalaureate: internationalBaccalaureate
          studentEthnicity:
            twoOrMoreRaces: twoOrMoreRaces
            hawaiianPacificlslander: hawaiianPacificlslander
            white: white
            asian: asian
            hispanic: hispanic
            black: black
            indianAlaskaNative: indianAlaskaNative
          blueRibbon: blueRibbon
          expensePerStudent: expensePerStudent
        schoolSubType: schoolSubType
        educationLevel: educationLevel
        teachers: teachers
        greatschools:
          gsId: gsId
          rating: rating
          url: url
        id: id
        ncesDistrictId: ncesDistrictId
        schoolRanking:
        - avgMathScore: avgMathScore
          current: current
          statePercentileScore: statePercentileScore
          stateRank: stateRank
          numberOfSchools: numberOfSchools
          avgReadingScore: avgReadingScore
          rankYear: rankYear
        - avgMathScore: avgMathScore
          current: current
          statePercentileScore: statePercentileScore
          stateRank: stateRank
          numberOfSchools: numberOfSchools
          avgReadingScore: avgReadingScore
          rankYear: rankYear
        website: website
        ncesSchoolId: ncesSchoolId
        address:
          country: country
          streetSide: streetSide
          city: city
          displayName: displayName
          postalCode: postalCode
          latitude: latitude
          businessName: businessName
          county: county
          unitType: unitType
          streetName: streetName
          formattedAddress: formattedAddress
          addressLine1: addressLine1
          mainAddressLine: mainAddressLine
          addressLine2: addressLine2
          addressLine3: addressLine3
          objectId: objectId
          addressLastLine: addressLastLine
          longitude: longitude
          unitValue: unitValue
          stateProvince: stateProvince
          urbanizationName: urbanizationName
          areaName1: areaName1
          areaName2: areaName2
          areaName3: areaName3
          areaName4: areaName4
          addressNumber: addressNumber
          postCode: postCode
          postCodeExt: postCodeExt
          placeName: placeName
          status: status
        schoolTypeDesc: schoolTypeDesc
        addressType: addressType
        educationLevelDesc: educationLevelDesc
        lowestGrade: lowestGrade
        studentTeacherRatio: studentTeacherRatio
        phone: phone
        highestGrade: highestGrade
        ncesDataYear: ncesDataYear
        gradeLevelsTaught:
          tenth: tenth
          eighth: eighth
          eleventh: eleventh
          second: second
          sixth: sixth
          third: third
          seventh: seventh
          twelfth: twelfth
          ninth: ninth
          fifth: fifth
          pk: pk
          fourth: fourth
          kg: kg
          first: first
        name: name
        assigned: assigned
        geometry:
          coordinates:
          - 0.8008281904610115
          - 0.8008281904610115
          type: type
        choice: choice
        status: status
      properties:
        id:
          type: string
        name:
          type: string
        assigned:
          type: string
        phone:
          type: string
        website:
          type: string
        addressType:
          type: string
        address:
          $ref: '#/components/schemas/address_1'
        lowestGrade:
          type: string
        highestGrade:
          type: string
        schoolType:
          type: string
        schoolTypeDesc:
          type: string
        schoolSubType:
          type: string
        schoolSubTypeDesc:
          type: string
        gender:
          type: string
        genderDesc:
          type: string
        educationLevel:
          type: string
        educationLevelDesc:
          type: string
        greatschools:
          $ref: '#/components/schemas/Greatschools'
        ncesSchoolId:
          type: string
        ncesDistrictId:
          type: string
        ncesDataYear:
          type: string
        schoolRanking:
          items:
            $ref: '#/components/schemas/SchoolRanking'
          type: array
        students:
          type: string
        teachers:
          type: string
        status:
          type: string
        studentTeacherRatio:
          type: string
        choice:
          type: string
        coextensiv:
          type: string
        schoolDistricts:
          $ref: '#/components/schemas/SchoolDistrict'
        schoolProfile:
          $ref: '#/components/schemas/SchoolProfile'
        gradeLevelsTaught:
          $ref: '#/components/schemas/GradeLevelsTaught'
        distance:
          $ref: '#/components/schemas/distance'
        geometry:
          $ref: '#/components/schemas/Geometry'
      type: object
    Geometry:
      example:
        coordinates:
        - 0.8008281904610115
        - 0.8008281904610115
        type: type
      properties:
        type:
          type: string
        coordinates:
          items:
            format: double
            type: number
          type: array
      type: object
    ErrorInfo_1:
      properties:
        errors:
          items:
            $ref: '#/components/schemas/ErrorCode'
          type: array
      type: object
    SchoolsNearByResponse:
      example:
        school:
        - schoolSubTypeDesc: schoolSubTypeDesc
          gender: gender
          distance:
            unit: unit
            value: value
          schoolType: schoolType
          coextensiv: coextensiv
          students: students
          schoolDistricts:
            totalSchools: totalSchools
            metro: metro
            districtUrl: districtUrl
            name: name
            districtType: districtType
            supervisoryUnionId: supervisoryUnionId
            areaInSqM: areaInSqM
            ncesDistrictId: ncesDistrictId
            districtEnrollment: districtEnrollment
          genderDesc: genderDesc
          schoolProfile:
            titleI: titleI
            freeOrReducedPriceLunches:
              reducedPriceLunchedCount: reducedPriceLunchedCount
              freeLunchesCount: freeLunchesCount
              totalCount: totalCount
            studentBelowPovertyPct: studentBelowPovertyPct
            advancePlacementClasses: advancePlacementClasses
            internationalBaccalaureate: internationalBaccalaureate
            studentEthnicity:
              twoOrMoreRaces: twoOrMoreRaces
              hawaiianPacificlslander: hawaiianPacificlslander
              white: white
              asian: asian
              hispanic: hispanic
              black: black
              indianAlaskaNative: indianAlaskaNative
            blueRibbon: blueRibbon
            expensePerStudent: expensePerStudent
          schoolSubType: schoolSubType
          educationLevel: educationLevel
          teachers: teachers
          greatschools:
            gsId: gsId
            rating: rating
            url: url
          id: id
          ncesDistrictId: ncesDistrictId
          schoolRanking:
          - avgMathScore: avgMathScore
            current: current
            statePercentileScore: statePercentileScore
            stateRank: stateRank
            numberOfSchools: numberOfSchools
            avgReadingScore: avgReadingScore
            rankYear: rankYear
          - avgMathScore: avgMathScore
            current: current
            statePercentileScore: statePercentileScore
            stateRank: stateRank
            numberOfSchools: numberOfSchools
            avgReadingScore: avgReadingScore
            rankYear: rankYear
          website: website
          ncesSchoolId: ncesSchoolId
          address:
            country: country
            streetSide: streetSide
            city: city
            displayName: displayName
            postalCode: postalCode
            latitude: latitude
            businessName: businessName
            county: county
            unitType: unitType
            streetName: streetName
            formattedAddress: formattedAddress
            addressLine1: addressLine1
            mainAddressLine: mainAddressLine
            addressLine2: addressLine2
            addressLine3: addressLine3
            objectId: objectId
            addressLastLine: addressLastLine
            longitude: longitude
            unitValue: unitValue
            stateProvince: stateProvince
            urbanizationName: urbanizationName
            areaName1: areaName1
            areaName2: areaName2
            areaName3: areaName3
            areaName4: areaName4
            addressNumber: addressNumber
            postCode: postCode
            postCodeExt: postCodeExt
            placeName: placeName
            status: status
          schoolTypeDesc: schoolTypeDesc
          addressType: addressType
          educationLevelDesc: educationLevelDesc
          lowestGrade: lowestGrade
          studentTeacherRatio: studentTeacherRatio
          phone: phone
          highestGrade: highestGrade
          ncesDataYear: ncesDataYear
          gradeLevelsTaught:
            tenth: tenth
            eighth: eighth
            eleventh: eleventh
            second: second
            sixth: sixth
            third: third
            seventh: seventh
            twelfth: twelfth
            ninth: ninth
            fifth: fifth
            pk: pk
            fourth: fourth
            kg: kg
            first: first
          name: name
          assigned: assigned
          geometry:
            coordinates:
            - 0.8008281904610115
            - 0.8008281904610115
            type: type
          choice: choice
          status: status
        - schoolSubTypeDesc: schoolSubTypeDesc
          gender: gender
          distance:
            unit: unit
            value: value
          schoolType: schoolType
          coextensiv: coextensiv
          students: students
          schoolDistricts:
            totalSchools: totalSchools
            metro: metro
            districtUrl: districtUrl
            name: name
            districtType: districtType
            supervisoryUnionId: supervisoryUnionId
            areaInSqM: areaInSqM
            ncesDistrictId: ncesDistrictId
            districtEnrollment: districtEnrollment
          genderDesc: genderDesc
          schoolProfile:
            titleI: titleI
            freeOrReducedPriceLunches:
              reducedPriceLunchedCount: reducedPriceLunchedCount
              freeLunchesCount: freeLunchesCount
              totalCount: totalCount
            studentBelowPovertyPct: studentBelowPovertyPct
            advancePlacementClasses: advancePlacementClasses
            internationalBaccalaureate: internationalBaccalaureate
            studentEthnicity:
              twoOrMoreRaces: twoOrMoreRaces
              hawaiianPacificlslander: hawaiianPacificlslander
              white: white
              asian: asian
              hispanic: hispanic
              black: black
              indianAlaskaNative: indianAlaskaNative
            blueRibbon: blueRibbon
            expensePerStudent: expensePerStudent
          schoolSubType: schoolSubType
          educationLevel: educationLevel
          teachers: teachers
          greatschools:
            gsId: gsId
            rating: rating
            url: url
          id: id
          ncesDistrictId: ncesDistrictId
          schoolRanking:
          - avgMathScore: avgMathScore
            current: current
            statePercentileScore: statePercentileScore
            stateRank: stateRank
            numberOfSchools: numberOfSchools
            avgReadingScore: avgReadingScore
            rankYear: rankYear
          - avgMathScore: avgMathScore
            current: current
            statePercentileScore: statePercentileScore
            stateRank: stateRank
            numberOfSchools: numberOfSchools
            avgReadingScore: avgReadingScore
            rankYear: rankYear
          website: website
          ncesSchoolId: ncesSchoolId
          address:
            country: country
            streetSide: streetSide
            city: city
            displayName: displayName
            postalCode: postalCode
            latitude: latitude
            businessName: businessName
            county: county
            unitType: unitType
            streetName: streetName
            formattedAddress: formattedAddress
            addressLine1: addressLine1
            mainAddressLine: mainAddressLine
            addressLine2: addressLine2
            addressLine3: addressLine3
            objectId: objectId
            addressLastLine: addressLastLine
            longitude: longitude
            unitValue: unitValue
            stateProvince: stateProvince
            urbanizationName: urbanizationName
            areaName1: areaName1
            areaName2: areaName2
            areaName3: areaName3
            areaName4: areaName4
            addressNumber: addressNumber
            postCode: postCode
            postCodeExt: postCodeExt
            placeName: placeName
            status: status
          schoolTypeDesc: schoolTypeDesc
          addressType: addressType
          educationLevelDesc: educationLevelDesc
          lowestGrade: lowestGrade
          studentTeacherRatio: studentTeacherRatio
          phone: phone
          highestGrade: highestGrade
          ncesDataYear: ncesDataYear
          gradeLevelsTaught:
            tenth: tenth
            eighth: eighth
            eleventh: eleventh
            second: second
            sixth: sixth
            third: third
            seventh: seventh
            twelfth: twelfth
            ninth: ninth
            fifth: fifth
            pk: pk
            fourth: fourth
            kg: kg
            first: first
          name: name
          assigned: assigned
          geometry:
            coordinates:
            - 0.8008281904610115
            - 0.8008281904610115
            type: type
          choice: choice
          status: status
        schoolDistrict:
          totalSchools: totalSchools
          metro: metro
          districtUrl: districtUrl
          name: name
          districtType: districtType
          supervisoryUnionId: supervisoryUnionId
          areaInSqM: areaInSqM
          ncesDistrictId: ncesDistrictId
          districtEnrollment: districtEnrollment
        matchedAddress:
          country: country
          streetSide: streetSide
          city: city
          displayName: displayName
          postalCode: postalCode
          latitude: latitude
          businessName: businessName
          county: county
          unitType: unitType
          streetName: streetName
          formattedAddress: formattedAddress
          addressLine1: addressLine1
          mainAddressLine: mainAddressLine
          addressLine2: addressLine2
          addressLine3: addressLine3
          objectId: objectId
          addressLastLine: addressLastLine
          longitude: longitude
          unitValue: unitValue
          stateProvince: stateProvince
          urbanizationName: urbanizationName
          areaName1: areaName1
          areaName2: areaName2
          areaName3: areaName3
          areaName4: areaName4
          addressNumber: addressNumber
          postCode: postCode
          postCodeExt: postCodeExt
          placeName: placeName
          status: status
      properties:
        matchedAddress:
          $ref: '#/components/schemas/address_1'
        school:
          items:
            $ref: '#/components/schemas/School'
          type: array
        schoolDistrict:
          $ref: '#/components/schemas/SchoolDistrict'
      type: object
    StudentEthnicity:
      example:
        twoOrMoreRaces: twoOrMoreRaces
        hawaiianPacificlslander: hawaiianPacificlslander
        white: white
        asian: asian
        hispanic: hispanic
        black: black
        indianAlaskaNative: indianAlaskaNative
      properties:
        indianAlaskaNative:
          type: string
        asian:
          type: string
        hispanic:
          type: string
        black:
          type: string
        white:
          type: string
        hawaiianPacificlslander:
          type: string
        twoOrMoreRaces:
          type: string
      type: object
    SchoolDistrict:
      example:
        totalSchools: totalSchools
        metro: metro
        districtUrl: districtUrl
        name: name
        districtType: districtType
        supervisoryUnionId: supervisoryUnionId
        areaInSqM: areaInSqM
        ncesDistrictId: ncesDistrictId
        districtEnrollment: districtEnrollment
      properties:
        ncesDistrictId:
          type: string
        name:
          type: string
        totalSchools:
          type: string
        districtType:
          type: string
        metro:
          type: string
        areaInSqM:
          type: string
        supervisoryUnionId:
          type: string
        districtEnrollment:
          type: string
        districtUrl:
          type: string
      type: object
    Greatschools:
      example:
        gsId: gsId
        rating: rating
        url: url
      properties:
        gsId:
          type: string
        url:
          type: string
        rating:
          type: string
      type: object
    ErrorCode:
      properties:
        errorCode:
          type: string
        errorDescription:
          type: string
      type: object
  securitySchemes:
    oAuth2Password:
      flows:
        implicit:
          authorizationUrl: https://api.precisely.com/oauth/token
          scopes:
            bearer token: put your bearer token here.
      type: oauth2
externalDocs:
  description: Online Documentation
  url: https://docs.precisely.com/docs/sftw/precisely-apis/main/en-us/webhelp/apis/index.html
