openapi: 3.0.1
info:
  contact:
    name: Precisely APIs Support
    url: https://support.precisely.com
  description: '

    Demographics. Audience Enrichment. Add local demographics and lifestyle

    segmentation to your audience profiles. The Demographics API returns

    household demographics and lifestyle characteristics with the input of an

    address, location coordinate, or geographic boundary. This service covers

    select countries.'
  license:
    name: Apache 2.0
    url: http://springdoc.org
  termsOfService: http://swagger.io/terms/
  title: Precisely APIs Getcitystateprovince API
  version: 18.1.0
servers:
- url: https://api.precisely.com
security:
- oAuth2Password:
  - ''
tags:
- name: Getcitystateprovince
paths:
  /addressverification/v1/getcitystateprovince/results.json:
    post:
      deprecated: false
      description: GetCityStateProvince returns a city and state/province for a given input postal code for U.S. and Canadian addresses.
      operationId: GetCityStateProvince
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetCityStateProvinceAPIRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCityStateProvinceAPIResponse'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInfo'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorInfo'
          description: Bad Request
        '500':
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
          description: Internal Server Error
      security:
      - oAuth2Password: []
      summary: GetCityStateProvince
      tags:
      - Getcitystateprovince
      x-codegen-request-body-name: InputAddress
      x-contentType: application/json
      x-accepts: application/json
components:
  schemas:
    GetPostalCodesAPIOutput_user_fields:
      example:
        name: name
        value: value
      properties:
        name:
          type: string
        value:
          type: string
      type: object
    GetCityStateProvinceAPIInputRow:
      example:
        user_fields:
        - name: name
          value: value
        - name: name
          value: value
        PostalCode: PostalCode
      properties:
        user_fields:
          description: These fields are returned, unmodified, in the user_fields section of the response.
          items:
            $ref: '#/components/schemas/GetPostalCodesAPIOutput_user_fields'
          type: array
        PostalCode:
          description: The validated ZIP Code or postal code.
          type: string
      type: object
    GetCityStateProvinceAPIResponse:
      example:
        Output:
        - Status: Status
          user_fields:
          - name: name
            value: value
          - name: name
            value: value
          StateProvince: StateProvince
          PostalCode: PostalCode
          Status.Description: Status.Description
          City: City
          Status.Code: Status.Code
          City.Type: City.Type
        - Status: Status
          user_fields:
          - name: name
            value: value
          - name: name
            value: value
          StateProvince: StateProvince
          PostalCode: PostalCode
          Status.Description: Status.Description
          City: City
          Status.Code: Status.Code
          City.Type: City.Type
      properties:
        Output:
          items:
            $ref: '#/components/schemas/GetCityStateProvinceAPIOutput'
          type: array
      type: object
    GetCityStateProvinceAPIInput:
      example:
        Row:
        - user_fields:
          - name: name
            value: value
          - name: name
            value: value
          PostalCode: PostalCode
        - user_fields:
          - name: name
            value: value
          - name: name
            value: value
          PostalCode: PostalCode
      properties:
        Row:
          items:
            $ref: '#/components/schemas/GetCityStateProvinceAPIInputRow'
          type: array
      type: object
    GetCityStateProvinceAPIOptions:
      example:
        OutputVanityCity: N
        PerformCanadianProcessing: Y
        MaximumResults: '10'
        PerformUSProcessing: Y
      properties:
        OutputVanityCity:
          default: N
          description: Output VanityCity.
          type: string
        PerformCanadianProcessing:
          default: Y
          description: PerformCanadianProcessing.
          type: string
        MaximumResults:
          default: '10'
          description: MaximumResults.
          type: string
        PerformUSProcessing:
          default: Y
          description: PerformUSProcessing.
          type: string
      type: object
    ErrorInfo:
      properties:
        errors:
          items:
            $ref: '#/components/schemas/ErrorCode'
          type: array
          xml:
            name: error
      type: object
      xml:
        name: errors
    GetCityStateProvinceAPIRequest:
      example:
        Input:
          Row:
          - user_fields:
            - name: name
              value: value
            - name: name
              value: value
            PostalCode: PostalCode
          - user_fields:
            - name: name
              value: value
            - name: name
              value: value
            PostalCode: PostalCode
        options:
          OutputVanityCity: N
          PerformCanadianProcessing: Y
          MaximumResults: '10'
          PerformUSProcessing: Y
      properties:
        options:
          $ref: '#/components/schemas/GetCityStateProvinceAPIOptions'
        Input:
          $ref: '#/components/schemas/GetCityStateProvinceAPIInput'
      type: object
    ErrorCode:
      properties:
        errorCode:
          type: string
        errorDescription:
          type: string
      type: object
    GetCityStateProvinceAPIOutput:
      example:
        Status: Status
        user_fields:
        - name: name
          value: value
        - name: name
          value: value
        StateProvince: StateProvince
        PostalCode: PostalCode
        Status.Description: Status.Description
        City: City
        Status.Code: Status.Code
        City.Type: City.Type
      properties:
        user_fields:
          description: These fields are returned, unmodified, in the user_fields section of the response.
          items:
            $ref: '#/components/schemas/GetPostalCodesAPIOutput_user_fields'
          type: array
        PostalCode:
          description: The validated ZIP Code or postal code.
          type: string
        City:
          description: City
          type: string
        City.Type:
          description: City.Type
          type: string
        StateProvince:
          description: The state or province.
          type: string
        Status:
          description: Reports the success or failure of the match attempt.
          type: string
        Status.Code:
          description: Reason for failure, if there is one.
          type: string
        Status.Description:
          description: Description of the problem, if there is one.
          type: string
      type: object
  securitySchemes:
    oAuth2Password:
      flows:
        implicit:
          authorizationUrl: https://api.precisely.com/oauth/token
          scopes:
            bearer token: put your bearer token here.
      type: oauth2
externalDocs:
  description: Online Documentation
  url: https://docs.precisely.com/docs/sftw/precisely-apis/main/en-us/webhelp/apis/index.html
