openapi: 3.0.1
info:
  contact:
    name: Precisely APIs Support
    url: https://support.precisely.com
  description: '

    Demographics. Audience Enrichment. Add local demographics and lifestyle

    segmentation to your audience profiles. The Demographics API returns

    household demographics and lifestyle characteristics with the input of an

    address, location coordinate, or geographic boundary. This service covers

    select countries.'
  license:
    name: Apache 2.0
    url: http://springdoc.org
  termsOfService: http://swagger.io/terms/
  title: Precisely APIs Zones  Service API
  version: 18.1.0
servers:
- url: https://api.precisely.com
security:
- oAuth2Password:
  - ''
tags:
- name: Zones  Service
paths:
  /zones/v1/travelboundary/bytime:
    get:
      description: Travel boundary based on travel time.
      operationId: getTravelBoundaryByTime
      parameters:
      - description: Starting point from where the travel boundary is calculated. Point in Lat,Long,coordsys format
        in: query
        name: point
        required: false
        schema:
          type: string
      - description: Starting address from where the travel boundary is calculated.
        in: query
        name: address
        required: false
        schema:
          type: string
      - description: Travel time used to calculate the travel boundary.
        in: query
        name: costs
        required: false
        schema:
          type: string
      - description: Travel time unit such as min(Minute), h(Hour), s(Second) or msec(Millisecond).
        in: query
        name: costUnit
        required: false
        schema:
          type: string
      - description: Mode of commute.
        in: query
        name: db
        required: false
        schema:
          type: string
      - description: 3 character ISO code or country name.
        in: query
        name: country
        required: false
        schema:
          type: string
      - description: Maximum distance to allow travel off the road network.
        in: query
        name: maxOffroadDistance
        required: false
        schema:
          type: string
      - description: MaxOffroad Distance Unit such as ft(Foot), km(Kilometer), mi(Mile), m(Meter) or yd(Yard).
        in: query
        name: maxOffroadDistanceUnit
        required: false
        schema:
          type: string
      - description: Desired coordinate system of the travel boundary.
        in: query
        name: destinationSrs
        required: false
        schema:
          type: string
      - description: Whether to include all roads in the calculation or just major roads.
        in: query
        name: majorRoads
        required: false
        schema:
          default: 'true'
          type: string
      - description: Whether to return holes, which are areas within the larger boundary that cannot be reached within the desired time
        in: query
        name: returnHoles
        required: false
        schema:
          type: string
      - description: Whether to return islands, which are small areas outside the main boundary that can be reached within the desired time
        in: query
        name: returnIslands
        required: false
        schema:
          type: string
      - description: Number between 0.0 and 1.0 where 0.0 is very simple and 1.0 means the most complex
        in: query
        name: simplificationFactor
        required: false
        schema:
          type: string
      - description: Style of banding to be used in the result
        in: query
        name: bandingStyle
        required: false
        schema:
          type: string
      - description: Whether routing calculation uses the historic traffic speeds
        in: query
        name: historicTrafficTimeBucket
        required: false
        schema:
          type: string
      - description: The speed to travel when going off a network road to find the travel boundary (for all road types).
        in: query
        name: defaultAmbientSpeed
        required: false
        schema:
          type: string
      - description: The unit of measure to use to calculate the ambient speed.
        in: query
        name: ambientSpeedUnit
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TravelBoundaries'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInfo_1'
          description: Bad Request
        '500':
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
      security:
      - oAuth2Password: []
      summary: Get TravelBoundary By Time.
      tags:
      - Zones  Service
      x-accepts: application/json
components:
  schemas:
    DirectionGeometry:
      example:
        coordinates:
        - - - - 6.027456183070403
              - 6.027456183070403
            - - 6.027456183070403
              - 6.027456183070403
          - - - 6.027456183070403
              - 6.027456183070403
            - - 6.027456183070403
              - 6.027456183070403
        - - - - 6.027456183070403
              - 6.027456183070403
            - - 6.027456183070403
              - 6.027456183070403
          - - - 6.027456183070403
              - 6.027456183070403
            - - 6.027456183070403
              - 6.027456183070403
        type: type
      properties:
        type:
          type: string
        coordinates:
          items:
            items:
              items:
                items:
                  format: double
                  type: number
                type: array
              type: array
            type: array
          type: array
      type: object
    TravelBoundary:
      example:
        costs:
        - costUnit: costUnit
          cost: 0.8008281904610115
          geometry:
            coordinates:
            - - - - 6.027456183070403
                  - 6.027456183070403
                - - 6.027456183070403
                  - 6.027456183070403
              - - - 6.027456183070403
                  - 6.027456183070403
                - - 6.027456183070403
                  - 6.027456183070403
            - - - - 6.027456183070403
                  - 6.027456183070403
                - - 6.027456183070403
                  - 6.027456183070403
              - - - 6.027456183070403
                  - 6.027456183070403
                - - 6.027456183070403
                  - 6.027456183070403
            type: type
        - costUnit: costUnit
          cost: 0.8008281904610115
          geometry:
            coordinates:
            - - - - 6.027456183070403
                  - 6.027456183070403
                - - 6.027456183070403
                  - 6.027456183070403
              - - - 6.027456183070403
                  - 6.027456183070403
                - - 6.027456183070403
                  - 6.027456183070403
            - - - - 6.027456183070403
                  - 6.027456183070403
                - - 6.027456183070403
                  - 6.027456183070403
              - - - 6.027456183070403
                  - 6.027456183070403
                - - 6.027456183070403
                  - 6.027456183070403
            type: type
      properties:
        costs:
          items:
            $ref: '#/components/schemas/Cost'
          properties:
            empty:
              type: boolean
          type: array
      type: object
    ErrorInfo_1:
      properties:
        errors:
          items:
            $ref: '#/components/schemas/ErrorCode'
          type: array
      type: object
    Cost:
      example:
        costUnit: costUnit
        cost: 0.8008281904610115
        geometry:
          coordinates:
          - - - - 6.027456183070403
                - 6.027456183070403
              - - 6.027456183070403
                - 6.027456183070403
            - - - 6.027456183070403
                - 6.027456183070403
              - - 6.027456183070403
                - 6.027456183070403
          - - - - 6.027456183070403
                - 6.027456183070403
              - - 6.027456183070403
                - 6.027456183070403
            - - - 6.027456183070403
                - 6.027456183070403
              - - 6.027456183070403
                - 6.027456183070403
          type: type
      properties:
        cost:
          type: number
        costUnit:
          type: string
        geometry:
          $ref: '#/components/schemas/DirectionGeometry'
      type: object
    TravelBoundaries:
      example:
        travelBoundary:
          costs:
          - costUnit: costUnit
            cost: 0.8008281904610115
            geometry:
              coordinates:
              - - - - 6.027456183070403
                    - 6.027456183070403
                  - - 6.027456183070403
                    - 6.027456183070403
                - - - 6.027456183070403
                    - 6.027456183070403
                  - - 6.027456183070403
                    - 6.027456183070403
              - - - - 6.027456183070403
                    - 6.027456183070403
                  - - 6.027456183070403
                    - 6.027456183070403
                - - - 6.027456183070403
                    - 6.027456183070403
                  - - 6.027456183070403
                    - 6.027456183070403
              type: type
          - costUnit: costUnit
            cost: 0.8008281904610115
            geometry:
              coordinates:
              - - - - 6.027456183070403
                    - 6.027456183070403
                  - - 6.027456183070403
                    - 6.027456183070403
                - - - 6.027456183070403
                    - 6.027456183070403
                  - - 6.027456183070403
                    - 6.027456183070403
              - - - - 6.027456183070403
                    - 6.027456183070403
                  - - 6.027456183070403
                    - 6.027456183070403
                - - - 6.027456183070403
                    - 6.027456183070403
                  - - 6.027456183070403
                    - 6.027456183070403
              type: type
      properties:
        travelBoundary:
          $ref: '#/components/schemas/TravelBoundary'
      type: object
    ErrorCode:
      properties:
        errorCode:
          type: string
        errorDescription:
          type: string
      type: object
  securitySchemes:
    oAuth2Password:
      flows:
        implicit:
          authorizationUrl: https://api.precisely.com/oauth/token
          scopes:
            bearer token: put your bearer token here.
      type: oauth2
externalDocs:
  description: Online Documentation
  url: https://docs.precisely.com/docs/sftw/precisely-apis/main/en-us/webhelp/apis/index.html
