openapi: 3.0.1
info:
  contact:
    name: Precisely APIs Support
    url: https://support.precisely.com
  description: '

    Demographics. Audience Enrichment. Add local demographics and lifestyle

    segmentation to your audience profiles. The Demographics API returns

    household demographics and lifestyle characteristics with the input of an

    address, location coordinate, or geographic boundary. This service covers

    select countries.'
  license:
    name: Apache 2.0
    url: http://springdoc.org
  termsOfService: http://swagger.io/terms/
  title: Precisely APIs Places  Service. API
  version: 18.1.0
servers:
- url: https://api.precisely.com
security:
- oAuth2Password:
  - ''
tags:
- name: Places  Service.
paths:
  /places/v1/poicount:
    post:
      description: Accepts a user-defined boundary as input and returns the Count number of POIs within the boundary. Additionally, user can request the count of filtered POIs by name, type, standard industrial classifications and category codes within the given polygon.
      operationId: getPOIsCount
      parameters:
      - in: header
        name: Content-Type
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PoiCountRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/poiCount'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInfo_1'
          description: Bad Request
        '500':
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
      security:
      - oAuth2Password: []
      summary: Points Of Interest Count
      tags:
      - Places  Service.
      x-contentType: application/json
      x-accepts: application/json
  /places/v1/poi/{id}:
    get:
      description: This service returns complete details of a chosen point of interest by an identifier. The identifier could be selected from Autocomplete API response.
      operationId: getPOIById
      parameters:
      - description: POI unique Identifier.
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/poi'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInfo_1'
          description: Bad Request
        '500':
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
      security:
      - oAuth2Password: []
      summary: Points Of Interest Details By Id
      tags:
      - Places  Service.
      x-accepts: application/json
components:
  schemas:
    PoiClassification:
      example:
        alternateIndustryCode: alternateIndustryCode
        sic:
          sicCode: sicCode
          primarySicCode: primarySicCode
          businessLine: businessLine
          sicCodeDescription: sicCodeDescription
          secondarySicCode: secondarySicCode
        category:
          tradeGroup: tradeGroup
          subClass: subClass
          tradeDivision: tradeDivision
          categoryCode: categoryCode
          class: class
      properties:
        sic:
          $ref: '#/components/schemas/Sic'
        category:
          $ref: '#/components/schemas/Category'
        alternateIndustryCode:
          type: string
      type: object
    Category:
      example:
        tradeGroup: tradeGroup
        subClass: subClass
        tradeDivision: tradeDivision
        categoryCode: categoryCode
        class: class
      properties:
        categoryCode:
          type: string
        tradeDivision:
          type: string
        tradeGroup:
          type: string
        subClass:
          type: string
        class:
          type: string
      type: object
    PoiCountRequest:
      example:
        fuzzyOnName: fuzzyOnName
        sicCode: sicCode
        name: name
        specificMatchOn: specificMatchOn
        geometry:
          coordinates:
          - 0.8008281904610115
          - 0.8008281904610115
          type: type
        categoryCode: categoryCode
        type: type
        matchMode: matchMode
        geometryAsText: geometryAsText
      properties:
        name:
          type: string
        type:
          type: string
        categoryCode:
          type: string
        sicCode:
          type: string
        fuzzyOnName:
          type: string
        matchMode:
          type: string
        specificMatchOn:
          type: string
        geometry:
          $ref: '#/components/schemas/Geometry'
        geometryAsText:
          type: string
      type: object
    address_1:
      example:
        country: country
        streetSide: streetSide
        city: city
        displayName: displayName
        postalCode: postalCode
        latitude: latitude
        businessName: businessName
        county: county
        unitType: unitType
        streetName: streetName
        formattedAddress: formattedAddress
        addressLine1: addressLine1
        mainAddressLine: mainAddressLine
        addressLine2: addressLine2
        addressLine3: addressLine3
        objectId: objectId
        addressLastLine: addressLastLine
        longitude: longitude
        unitValue: unitValue
        stateProvince: stateProvince
        urbanizationName: urbanizationName
        areaName1: areaName1
        areaName2: areaName2
        areaName3: areaName3
        areaName4: areaName4
        addressNumber: addressNumber
        postCode: postCode
        postCodeExt: postCodeExt
        placeName: placeName
        status: status
      properties:
        objectId:
          type: string
        displayName:
          type: string
        streetSide:
          type: string
        businessName:
          type: string
        addressLine1:
          type: string
        addressLine2:
          type: string
        addressLine3:
          type: string
        city:
          type: string
        stateProvince:
          type: string
        county:
          type: string
        postalCode:
          type: string
        latitude:
          type: string
        longitude:
          type: string
        status:
          type: string
        urbanizationName:
          type: string
        formattedAddress:
          type: string
        mainAddressLine:
          type: string
        addressLastLine:
          type: string
        placeName:
          type: string
        areaName1:
          type: string
        areaName2:
          type: string
        areaName3:
          type: string
        areaName4:
          type: string
        postCode:
          type: string
        postCodeExt:
          type: string
        country:
          type: string
        addressNumber:
          type: string
        streetName:
          type: string
        unitType:
          type: string
        unitValue:
          type: string
      type: object
    ParentBusiness:
      example:
        address:
          country: country
          streetSide: streetSide
          city: city
          displayName: displayName
          postalCode: postalCode
          latitude: latitude
          businessName: businessName
          county: county
          unitType: unitType
          streetName: streetName
          formattedAddress: formattedAddress
          addressLine1: addressLine1
          mainAddressLine: mainAddressLine
          addressLine2: addressLine2
          addressLine3: addressLine3
          objectId: objectId
          addressLastLine: addressLastLine
          longitude: longitude
          unitValue: unitValue
          stateProvince: stateProvince
          urbanizationName: urbanizationName
          areaName1: areaName1
          areaName2: areaName2
          areaName3: areaName3
          areaName4: areaName4
          addressNumber: addressNumber
          postCode: postCode
          postCodeExt: postCodeExt
          placeName: placeName
          status: status
        name: name
        id: id
      properties:
        id:
          type: string
        name:
          type: string
        address:
          $ref: '#/components/schemas/address_1'
      type: object
    distance:
      example:
        unit: unit
        value: value
      properties:
        unit:
          type: string
        value:
          type: string
      type: object
    DomesticUltimateBusiness:
      example:
        address:
          country: country
          streetSide: streetSide
          city: city
          displayName: displayName
          postalCode: postalCode
          latitude: latitude
          businessName: businessName
          county: county
          unitType: unitType
          streetName: streetName
          formattedAddress: formattedAddress
          addressLine1: addressLine1
          mainAddressLine: mainAddressLine
          addressLine2: addressLine2
          addressLine3: addressLine3
          objectId: objectId
          addressLastLine: addressLastLine
          longitude: longitude
          unitValue: unitValue
          stateProvince: stateProvince
          urbanizationName: urbanizationName
          areaName1: areaName1
          areaName2: areaName2
          areaName3: areaName3
          areaName4: areaName4
          addressNumber: addressNumber
          postCode: postCode
          postCodeExt: postCodeExt
          placeName: placeName
          status: status
        name: name
        id: id
      properties:
        id:
          type: string
        name:
          type: string
        address:
          $ref: '#/components/schemas/address_1'
      type: object
    Geometry:
      example:
        coordinates:
        - 0.8008281904610115
        - 0.8008281904610115
        type: type
      properties:
        type:
          type: string
        coordinates:
          items:
            format: double
            type: number
          type: array
      type: object
    ErrorInfo_1:
      properties:
        errors:
          items:
            $ref: '#/components/schemas/ErrorCode'
          type: array
      type: object
    salesVolume:
      example:
        currencyCode: currencyCode
        worldBaseCurrencyCode: worldBaseCurrencyCode
        value: value
      properties:
        currencyCode:
          type: string
        worldBaseCurrencyCode:
          type: string
        value:
          type: string
      type: object
    businessId:
      example:
        type: type
        value: value
      properties:
        type:
          type: string
        value:
          type: string
      type: object
    EmployeeCount:
      example:
        inLocalBranch: inLocalBranch
        inOrganization: inOrganization
      properties:
        inLocalBranch:
          type: string
        inOrganization:
          type: string
      type: object
    Sic:
      example:
        sicCode: sicCode
        primarySicCode: primarySicCode
        businessLine: businessLine
        sicCodeDescription: sicCodeDescription
        secondarySicCode: secondarySicCode
      properties:
        businessLine:
          type: string
        sicCode:
          type: string
        sicCodeDescription:
          type: string
        primarySicCode:
          type: string
        secondarySicCode:
          type: string
      type: object
    poiCount:
      example:
        totalPoisFound: 0
      properties:
        totalPoisFound:
          format: int32
          type: integer
      type: object
    GlobalUltimateBusiness:
      example:
        address:
          country: country
          streetSide: streetSide
          city: city
          displayName: displayName
          postalCode: postalCode
          latitude: latitude
          businessName: businessName
          county: county
          unitType: unitType
          streetName: streetName
          formattedAddress: formattedAddress
          addressLine1: addressLine1
          mainAddressLine: mainAddressLine
          addressLine2: addressLine2
          addressLine3: addressLine3
          objectId: objectId
          addressLastLine: addressLastLine
          longitude: longitude
          unitValue: unitValue
          stateProvince: stateProvince
          urbanizationName: urbanizationName
          areaName1: areaName1
          areaName2: areaName2
          areaName3: areaName3
          areaName4: areaName4
          addressNumber: addressNumber
          postCode: postCode
          postCodeExt: postCodeExt
          placeName: placeName
          status: status
        name: name
        id: id
      properties:
        id:
          type: string
        name:
          type: string
        address:
          $ref: '#/components/schemas/address_1'
      type: object
    poi:
      example:
        parentPbkey: parentPbkey
        distance:
          unit: unit
          value: value
        salesVolume:
        - currencyCode: currencyCode
          worldBaseCurrencyCode: worldBaseCurrencyCode
          value: value
        - currencyCode: currencyCode
          worldBaseCurrencyCode: worldBaseCurrencyCode
          value: value
        hierarchyCode: hierarchyCode
        businessId:
          type: type
          value: value
        open24Hours: open24Hours
        employeeCount:
          inLocalBranch: inLocalBranch
          inOrganization: inOrganization
        subsidaryIndicator: subsidaryIndicator
        domesticUltimateBusiness:
          address:
            country: country
            streetSide: streetSide
            city: city
            displayName: displayName
            postalCode: postalCode
            latitude: latitude
            businessName: businessName
            county: county
            unitType: unitType
            streetName: streetName
            formattedAddress: formattedAddress
            addressLine1: addressLine1
            mainAddressLine: mainAddressLine
            addressLine2: addressLine2
            addressLine3: addressLine3
            objectId: objectId
            addressLastLine: addressLastLine
            longitude: longitude
            unitValue: unitValue
            stateProvince: stateProvince
            urbanizationName: urbanizationName
            areaName1: areaName1
            areaName2: areaName2
            areaName3: areaName3
            areaName4: areaName4
            addressNumber: addressNumber
            postCode: postCode
            postCodeExt: postCodeExt
            placeName: placeName
            status: status
          name: name
          id: id
        globalUltimateBusiness:
          address:
            country: country
            streetSide: streetSide
            city: city
            displayName: displayName
            postalCode: postalCode
            latitude: latitude
            businessName: businessName
            county: county
            unitType: unitType
            streetName: streetName
            formattedAddress: formattedAddress
            addressLine1: addressLine1
            mainAddressLine: mainAddressLine
            addressLine2: addressLine2
            addressLine3: addressLine3
            objectId: objectId
            addressLastLine: addressLastLine
            longitude: longitude
            unitValue: unitValue
            stateProvince: stateProvince
            urbanizationName: urbanizationName
            areaName1: areaName1
            areaName2: areaName2
            areaName3: areaName3
            areaName4: areaName4
            addressNumber: addressNumber
            postCode: postCode
            postCodeExt: postCodeExt
            placeName: placeName
            status: status
          name: name
          id: id
        familyMembers: familyMembers
        poiClassification:
          alternateIndustryCode: alternateIndustryCode
          sic:
            sicCode: sicCode
            primarySicCode: primarySicCode
            businessLine: businessLine
            sicCodeDescription: sicCodeDescription
            secondarySicCode: secondarySicCode
          category:
            tradeGroup: tradeGroup
            subClass: subClass
            tradeDivision: tradeDivision
            categoryCode: categoryCode
            class: class
        globalUltimateIndicator: globalUltimateIndicator
        tradeName: tradeName
        geocodeConfidence: geocodeConfidence
        goodsAgentCodeDescription: goodsAgentCodeDescription
        organizationStatusCodeDescription: organizationStatusCodeDescription
        subsidaryIndicatorDescription: subsidaryIndicatorDescription
        parentBusiness:
          address:
            country: country
            streetSide: streetSide
            city: city
            displayName: displayName
            postalCode: postalCode
            latitude: latitude
            businessName: businessName
            county: county
            unitType: unitType
            streetName: streetName
            formattedAddress: formattedAddress
            addressLine1: addressLine1
            mainAddressLine: mainAddressLine
            addressLine2: addressLine2
            addressLine3: addressLine3
            objectId: objectId
            addressLastLine: addressLastLine
            longitude: longitude
            unitValue: unitValue
            stateProvince: stateProvince
            urbanizationName: urbanizationName
            areaName1: areaName1
            areaName2: areaName2
            areaName3: areaName3
            areaName4: areaName4
            addressNumber: addressNumber
            postCode: postCode
            postCodeExt: postCodeExt
            placeName: placeName
            status: status
          name: name
          id: id
        id: id
        poiId: poiId
        ceoName: ceoName
        yearStart: yearStart
        franchiseName: franchiseName
        brandName: brandName
        tickerSymbol: tickerSymbol
        contactDetails:
          address:
            country: country
            streetSide: streetSide
            city: city
            displayName: displayName
            postalCode: postalCode
            latitude: latitude
            businessName: businessName
            county: county
            unitType: unitType
            streetName: streetName
            formattedAddress: formattedAddress
            addressLine1: addressLine1
            mainAddressLine: mainAddressLine
            addressLine2: addressLine2
            addressLine3: addressLine3
            objectId: objectId
            addressLastLine: addressLastLine
            longitude: longitude
            unitValue: unitValue
            stateProvince: stateProvince
            urbanizationName: urbanizationName
            areaName1: areaName1
            areaName2: areaName2
            areaName3: areaName3
            areaName4: areaName4
            addressNumber: addressNumber
            postCode: postCode
            postCodeExt: postCodeExt
            placeName: placeName
            status: status
          phone: phone
          countryAccessCode: countryAccessCode
          fax: fax
          email: email
          url: url
        ceoTitle: ceoTitle
        goodsAgentCode: goodsAgentCode
        organizationStatusCode: organizationStatusCode
        relevanceScore: relevanceScore
        pbkey: pbkey
        name: name
        exchangeName: exchangeName
        geometry:
          coordinates:
          - 0.8008281904610115
          - 0.8008281904610115
          type: type
        legalStatusCode: legalStatusCode
      properties:
        id:
          type: string
        poiId:
          type: string
        name:
          type: string
        pbkey:
          type: string
        parentPbkey:
          type: string
        geocodeConfidence:
          type: string
        brandName:
          type: string
        tradeName:
          type: string
        franchiseName:
          type: string
        open24Hours:
          type: string
        distance:
          $ref: '#/components/schemas/distance'
        businessId:
          $ref: '#/components/schemas/businessId'
        relevanceScore:
          type: string
        contactDetails:
          $ref: '#/components/schemas/ContactDetails'
        poiClassification:
          $ref: '#/components/schemas/PoiClassification'
        salesVolume:
          items:
            $ref: '#/components/schemas/salesVolume'
          type: array
        employeeCount:
          $ref: '#/components/schemas/EmployeeCount'
        yearStart:
          type: string
        goodsAgentCode:
          type: string
        goodsAgentCodeDescription:
          type: string
        legalStatusCode:
          type: string
        organizationStatusCode:
          type: string
        organizationStatusCodeDescription:
          type: string
        subsidaryIndicator:
          type: string
        subsidaryIndicatorDescription:
          type: string
        parentBusiness:
          $ref: '#/components/schemas/ParentBusiness'
        domesticUltimateBusiness:
          $ref: '#/components/schemas/DomesticUltimateBusiness'
        globalUltimateIndicator:
          type: string
        globalUltimateBusiness:
          $ref: '#/components/schemas/GlobalUltimateBusiness'
        familyMembers:
          type: string
        hierarchyCode:
          type: string
        tickerSymbol:
          type: string
        exchangeName:
          type: string
        ceoName:
          type: string
        ceoTitle:
          type: string
        geometry:
          $ref: '#/components/schemas/Geometry'
      type: object
    ContactDetails:
      example:
        address:
          country: country
          streetSide: streetSide
          city: city
          displayName: displayName
          postalCode: postalCode
          latitude: latitude
          businessName: businessName
          county: county
          unitType: unitType
          streetName: streetName
          formattedAddress: formattedAddress
          addressLine1: addressLine1
          mainAddressLine: mainAddressLine
          addressLine2: addressLine2
          addressLine3: addressLine3
          objectId: objectId
          addressLastLine: addressLastLine
          longitude: longitude
          unitValue: unitValue
          stateProvince: stateProvince
          urbanizationName: urbanizationName
          areaName1: areaName1
          areaName2: areaName2
          areaName3: areaName3
          areaName4: areaName4
          addressNumber: addressNumber
          postCode: postCode
          postCodeExt: postCodeExt
          placeName: placeName
          status: status
        phone: phone
        countryAccessCode: countryAccessCode
        fax: fax
        email: email
        url: url
      properties:
        address:
          $ref: '#/components/schemas/address_1'
        phone:
          type: string
        fax:
          type: string
        countryAccessCode:
          type: string
        email:
          type: string
        url:
          type: string
      type: object
    ErrorCode:
      properties:
        errorCode:
          type: string
        errorDescription:
          type: string
      type: object
  securitySchemes:
    oAuth2Password:
      flows:
        implicit:
          authorizationUrl: https://api.precisely.com/oauth/token
          scopes:
            bearer token: put your bearer token here.
      type: oauth2
externalDocs:
  description: Online Documentation
  url: https://docs.precisely.com/docs/sftw/precisely-apis/main/en-us/webhelp/apis/index.html
