openapi: 3.0.1
info:
  contact:
    name: Precisely APIs Support
    url: https://support.precisely.com
  description: '

    Demographics. Audience Enrichment. Add local demographics and lifestyle

    segmentation to your audience profiles. The Demographics API returns

    household demographics and lifestyle characteristics with the input of an

    address, location coordinate, or geographic boundary. This service covers

    select countries.'
  license:
    name: Apache 2.0
    url: http://springdoc.org
  termsOfService: http://swagger.io/terms/
  title: Precisely APIs Ahj API
  version: 18.1.0
servers:
- url: https://api.precisely.com
security:
- oAuth2Password:
  - ''
tags:
- name: Ahj
paths:
  /911/v1/ahj-psap/bylocation:
    get:
      description: Accepts latitude & longitude as input and Returns contact details for Authorities Having Jurisdiction (AHJ) on-behalf-of local Public Safety Answering Points (PSAP). 911/PSAP accepts a location coordinate and returns PSAP contact data plus contact data for an AHJ to communicate directly with a PSAP. Details include agency name, phone number, city name, coverage, contact person's details, site details and mailing addresses for EMS, Fire, and Police PSAP contacts.
      operationId: getAHJPlusPSAPByLocation
      parameters:
      - description: Longitude of the location.
        in: query
        name: longitude
        required: true
        schema:
          type: string
      - description: Latitude of the location.
        in: query
        name: latitude
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AHJPlusPSAPResponse'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInfo_1'
          description: Bad Request
        '500':
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
      security:
      - oAuth2Password: []
      summary: AHJ & PSAP By Location
      tags:
      - Ahj
      x-accepts: application/json
  /911/v1/ahj-psap/byaddress:
    get:
      description: Accepts addresses as input and Returns contact details for Authorities Having Jurisdiction (AHJ) on-behalf-of local Public Safety Answering Points (PSAP). 911/PSAP accepts an address and returns PSAP contact data plus contact data for an AHJ to communicate directly with a PSAP. Details include agency name, phone number, city name, coverage, contact person's details, site details and mailing addresses for EMS, Fire, and Police PSAP contacts.
      operationId: getAHJPlusPSAPByAddress
      parameters:
      - description: The address to be searched.
        in: query
        name: address
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AHJPlusPSAPResponse'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInfo_1'
          description: Bad Request
        '500':
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
      security:
      - oAuth2Password: []
      summary: AHJ & PSAP By Address.
      tags:
      - Ahj
      x-accepts: application/json
  /911/v1/ahj-psap/byfccid:
    get:
      description: Accepts fccid as input and Returns contact details for Authorities Having Jurisdiction (AHJ) on-behalf-of local Public Safety Answering Points (PSAP). 911/PSAP accepts a location coordinate and returns PSAP contact data plus contact data for an AHJ to communicate directly with a PSAP. Details include agency name, phone number, city name, coverage, contact person's details, site details and mailing addresses for EMS, Fire, and Police PSAP contacts.
      operationId: searchByFccId
      parameters:
      - description: fccId
        in: query
        name: fccId
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AHJPlusPSAPResponse'
          description: OK
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInfo_1'
          description: Bad Request
        '500':
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
      security:
      - oAuth2Password: []
      summary: AHJ & PSAP By Fccid
      tags:
      - Ahj
      x-accepts: application/json
components:
  schemas:
    AHJ:
      example:
        coverage:
          area: area
          comments: comments
          exceptions: exceptions
        comments: comments
        agency: agency
        phone: phone
        mailingAddress:
          country: country
          streetSide: streetSide
          city: city
          displayName: displayName
          postalCode: postalCode
          latitude: latitude
          businessName: businessName
          county: county
          unitType: unitType
          streetName: streetName
          formattedAddress: formattedAddress
          addressLine1: addressLine1
          mainAddressLine: mainAddressLine
          addressLine2: addressLine2
          addressLine3: addressLine3
          objectId: objectId
          addressLastLine: addressLastLine
          longitude: longitude
          unitValue: unitValue
          stateProvince: stateProvince
          urbanizationName: urbanizationName
          areaName1: areaName1
          areaName2: areaName2
          areaName3: areaName3
          areaName4: areaName4
          addressNumber: addressNumber
          postCode: postCode
          postCodeExt: postCodeExt
          placeName: placeName
          status: status
        ahjId: ahjId
        contactPerson:
          firstName: firstName
          lastName: lastName
          comments: comments
          phone: phone
          prefix: prefix
          fullName: fullName
          title: title
          fax: fax
          additionalDetails: additionalDetails
          email: email
        fccId: fccId
        type: type
        ahjType: ahjType
      properties:
        ahjType:
          type: string
        ahjId:
          type: string
        type:
          type: string
        fccId:
          type: string
        agency:
          type: string
        phone:
          type: string
        comments:
          type: string
        coverage:
          $ref: '#/components/schemas/coverage'
        contactPerson:
          $ref: '#/components/schemas/contactPerson'
        mailingAddress:
          $ref: '#/components/schemas/AHJmailingAddress'
      type: object
    AHJPlusPSAPResponse:
      example:
        psap:
          coverage:
            area: area
            comments: comments
            exceptions: exceptions
          agency: agency
          phone: phone
          mailingAddress:
            country: country
            streetSide: streetSide
            city: city
            displayName: displayName
            postalCode: postalCode
            latitude: latitude
            businessName: businessName
            county: county
            unitType: unitType
            streetName: streetName
            formattedAddress: formattedAddress
            addressLine1: addressLine1
            mainAddressLine: mainAddressLine
            addressLine2: addressLine2
            addressLine3: addressLine3
            objectId: objectId
            addressLastLine: addressLastLine
            longitude: longitude
            unitValue: unitValue
            stateProvince: stateProvince
            urbanizationName: urbanizationName
            areaName1: areaName1
            areaName2: areaName2
            areaName3: areaName3
            areaName4: areaName4
            addressNumber: addressNumber
            postCode: postCode
            postCodeExt: postCodeExt
            placeName: placeName
            status: status
          count: 0
          county:
            name: name
            fips: fips
          contactPerson:
            firstName: firstName
            lastName: lastName
            comments: comments
            phone: phone
            prefix: prefix
            fullName: fullName
            title: title
            fax: fax
            additionalDetails: additionalDetails
            email: email
          fccId: fccId
          psapId: psapId
          type: type
          siteDetails:
            address:
              country: country
              streetSide: streetSide
              city: city
              displayName: displayName
              postalCode: postalCode
              latitude: latitude
              businessName: businessName
              county: county
              unitType: unitType
              streetName: streetName
              formattedAddress: formattedAddress
              addressLine1: addressLine1
              mainAddressLine: mainAddressLine
              addressLine2: addressLine2
              addressLine3: addressLine3
              objectId: objectId
              addressLastLine: addressLastLine
              longitude: longitude
              unitValue: unitValue
              stateProvince: stateProvince
              urbanizationName: urbanizationName
              areaName1: areaName1
              areaName2: areaName2
              areaName3: areaName3
              areaName4: areaName4
              addressNumber: addressNumber
              postCode: postCode
              postCodeExt: postCodeExt
              placeName: placeName
              status: status
            phone: phone
            contactName: contactName
            fax: fax
            email: email
        count: 0
        ahjs:
          ahjs:
          - coverage:
              area: area
              comments: comments
              exceptions: exceptions
            comments: comments
            agency: agency
            phone: phone
            mailingAddress:
              country: country
              streetSide: streetSide
              city: city
              displayName: displayName
              postalCode: postalCode
              latitude: latitude
              businessName: businessName
              county: county
              unitType: unitType
              streetName: streetName
              formattedAddress: formattedAddress
              addressLine1: addressLine1
              mainAddressLine: mainAddressLine
              addressLine2: addressLine2
              addressLine3: addressLine3
              objectId: objectId
              addressLastLine: addressLastLine
              longitude: longitude
              unitValue: unitValue
              stateProvince: stateProvince
              urbanizationName: urbanizationName
              areaName1: areaName1
              areaName2: areaName2
              areaName3: areaName3
              areaName4: areaName4
              addressNumber: addressNumber
              postCode: postCode
              postCodeExt: postCodeExt
              placeName: placeName
              status: status
            ahjId: ahjId
            contactPerson:
              firstName: firstName
              lastName: lastName
              comments: comments
              phone: phone
              prefix: prefix
              fullName: fullName
              title: title
              fax: fax
              additionalDetails: additionalDetails
              email: email
            fccId: fccId
            type: type
            ahjType: ahjType
          - coverage:
              area: area
              comments: comments
              exceptions: exceptions
            comments: comments
            agency: agency
            phone: phone
            mailingAddress:
              country: country
              streetSide: streetSide
              city: city
              displayName: displayName
              postalCode: postalCode
              latitude: latitude
              businessName: businessName
              county: county
              unitType: unitType
              streetName: streetName
              formattedAddress: formattedAddress
              addressLine1: addressLine1
              mainAddressLine: mainAddressLine
              addressLine2: addressLine2
              addressLine3: addressLine3
              objectId: objectId
              addressLastLine: addressLastLine
              longitude: longitude
              unitValue: unitValue
              stateProvince: stateProvince
              urbanizationName: urbanizationName
              areaName1: areaName1
              areaName2: areaName2
              areaName3: areaName3
              areaName4: areaName4
              addressNumber: addressNumber
              postCode: postCode
              postCodeExt: postCodeExt
              placeName: placeName
              status: status
            ahjId: ahjId
            contactPerson:
              firstName: firstName
              lastName: lastName
              comments: comments
              phone: phone
              prefix: prefix
              fullName: fullName
              title: title
              fax: fax
              additionalDetails: additionalDetails
              email: email
            fccId: fccId
            type: type
            ahjType: ahjType
      properties:
        ahjs:
          $ref: '#/components/schemas/AHJList'
        psap:
          $ref: '#/components/schemas/PSAPResponse'
        count:
          format: int32
          type: integer
      type: object
    PSAPResponse:
      example:
        coverage:
          area: area
          comments: comments
          exceptions: exceptions
        agency: agency
        phone: phone
        mailingAddress:
          country: country
          streetSide: streetSide
          city: city
          displayName: displayName
          postalCode: postalCode
          latitude: latitude
          businessName: businessName
          county: county
          unitType: unitType
          streetName: streetName
          formattedAddress: formattedAddress
          addressLine1: addressLine1
          mainAddressLine: mainAddressLine
          addressLine2: addressLine2
          addressLine3: addressLine3
          objectId: objectId
          addressLastLine: addressLastLine
          longitude: longitude
          unitValue: unitValue
          stateProvince: stateProvince
          urbanizationName: urbanizationName
          areaName1: areaName1
          areaName2: areaName2
          areaName3: areaName3
          areaName4: areaName4
          addressNumber: addressNumber
          postCode: postCode
          postCodeExt: postCodeExt
          placeName: placeName
          status: status
        count: 0
        county:
          name: name
          fips: fips
        contactPerson:
          firstName: firstName
          lastName: lastName
          comments: comments
          phone: phone
          prefix: prefix
          fullName: fullName
          title: title
          fax: fax
          additionalDetails: additionalDetails
          email: email
        fccId: fccId
        psapId: psapId
        type: type
        siteDetails:
          address:
            country: country
            streetSide: streetSide
            city: city
            displayName: displayName
            postalCode: postalCode
            latitude: latitude
            businessName: businessName
            county: county
            unitType: unitType
            streetName: streetName
            formattedAddress: formattedAddress
            addressLine1: addressLine1
            mainAddressLine: mainAddressLine
            addressLine2: addressLine2
            addressLine3: addressLine3
            objectId: objectId
            addressLastLine: addressLastLine
            longitude: longitude
            unitValue: unitValue
            stateProvince: stateProvince
            urbanizationName: urbanizationName
            areaName1: areaName1
            areaName2: areaName2
            areaName3: areaName3
            areaName4: areaName4
            addressNumber: addressNumber
            postCode: postCode
            postCodeExt: postCodeExt
            placeName: placeName
            status: status
          phone: phone
          contactName: contactName
          fax: fax
          email: email
      properties:
        psapId:
          type: string
        fccId:
          type: string
        type:
          type: string
        count:
          format: int32
          type: integer
        agency:
          type: string
        phone:
          type: string
        county:
          $ref: '#/components/schemas/county'
        coverage:
          $ref: '#/components/schemas/coverage'
        contactPerson:
          $ref: '#/components/schemas/contactPerson'
        siteDetails:
          $ref: '#/components/schemas/siteDetails'
        mailingAddress:
          $ref: '#/components/schemas/AHJmailingAddress'
      type: object
    siteDetails:
      example:
        address:
          country: country
          streetSide: streetSide
          city: city
          displayName: displayName
          postalCode: postalCode
          latitude: latitude
          businessName: businessName
          county: county
          unitType: unitType
          streetName: streetName
          formattedAddress: formattedAddress
          addressLine1: addressLine1
          mainAddressLine: mainAddressLine
          addressLine2: addressLine2
          addressLine3: addressLine3
          objectId: objectId
          addressLastLine: addressLastLine
          longitude: longitude
          unitValue: unitValue
          stateProvince: stateProvince
          urbanizationName: urbanizationName
          areaName1: areaName1
          areaName2: areaName2
          areaName3: areaName3
          areaName4: areaName4
          addressNumber: addressNumber
          postCode: postCode
          postCodeExt: postCodeExt
          placeName: placeName
          status: status
        phone: phone
        contactName: contactName
        fax: fax
        email: email
      properties:
        phone:
          type: string
        fax:
          type: string
        contactName:
          type: string
        email:
          type: string
        address:
          $ref: '#/components/schemas/AHJmailingAddress'
      type: object
    coverage:
      example:
        area: area
        comments: comments
        exceptions: exceptions
      properties:
        area:
          type: string
        comments:
          type: string
        exceptions:
          type: string
      type: object
    AHJList:
      example:
        ahjs:
        - coverage:
            area: area
            comments: comments
            exceptions: exceptions
          comments: comments
          agency: agency
          phone: phone
          mailingAddress:
            country: country
            streetSide: streetSide
            city: city
            displayName: displayName
            postalCode: postalCode
            latitude: latitude
            businessName: businessName
            county: county
            unitType: unitType
            streetName: streetName
            formattedAddress: formattedAddress
            addressLine1: addressLine1
            mainAddressLine: mainAddressLine
            addressLine2: addressLine2
            addressLine3: addressLine3
            objectId: objectId
            addressLastLine: addressLastLine
            longitude: longitude
            unitValue: unitValue
            stateProvince: stateProvince
            urbanizationName: urbanizationName
            areaName1: areaName1
            areaName2: areaName2
            areaName3: areaName3
            areaName4: areaName4
            addressNumber: addressNumber
            postCode: postCode
            postCodeExt: postCodeExt
            placeName: placeName
            status: status
          ahjId: ahjId
          contactPerson:
            firstName: firstName
            lastName: lastName
            comments: comments
            phone: phone
            prefix: prefix
            fullName: fullName
            title: title
            fax: fax
            additionalDetails: additionalDetails
            email: email
          fccId: fccId
          type: type
          ahjType: ahjType
        - coverage:
            area: area
            comments: comments
            exceptions: exceptions
          comments: comments
          agency: agency
          phone: phone
          mailingAddress:
            country: country
            streetSide: streetSide
            city: city
            displayName: displayName
            postalCode: postalCode
            latitude: latitude
            businessName: businessName
            county: county
            unitType: unitType
            streetName: streetName
            formattedAddress: formattedAddress
            addressLine1: addressLine1
            mainAddressLine: mainAddressLine
            addressLine2: addressLine2
            addressLine3: addressLine3
            objectId: objectId
            addressLastLine: addressLastLine
            longitude: longitude
            unitValue: unitValue
            stateProvince: stateProvince
            urbanizationName: urbanizationName
            areaName1: areaName1
            areaName2: areaName2
            areaName3: areaName3
            areaName4: areaName4
            addressNumber: addressNumber
            postCode: postCode
            postCodeExt: postCodeExt
            placeName: placeName
            status: status
          ahjId: ahjId
          contactPerson:
            firstName: firstName
            lastName: lastName
            comments: comments
            phone: phone
            prefix: prefix
            fullName: fullName
            title: title
            fax: fax
            additionalDetails: additionalDetails
            email: email
          fccId: fccId
          type: type
          ahjType: ahjType
      properties:
        ahjs:
          items:
            $ref: '#/components/schemas/AHJ'
          type: array
      type: object
    contactPerson:
      example:
        firstName: firstName
        lastName: lastName
        comments: comments
        phone: phone
        prefix: prefix
        fullName: fullName
        title: title
        fax: fax
        additionalDetails: additionalDetails
        email: email
      properties:
        title:
          type: string
        fullName:
          type: string
        prefix:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
        fax:
          type: string
        email:
          type: string
        comments:
          type: string
        additionalDetails:
          type: string
      type: object
    ErrorInfo_1:
      properties:
        errors:
          items:
            $ref: '#/components/schemas/ErrorCode'
          type: array
      type: object
    county:
      example:
        name: name
        fips: fips
      properties:
        name:
          type: string
        fips:
          type: string
      type: object
    AHJmailingAddress:
      example:
        country: country
        streetSide: streetSide
        city: city
        displayName: displayName
        postalCode: postalCode
        latitude: latitude
        businessName: businessName
        county: county
        unitType: unitType
        streetName: streetName
        formattedAddress: formattedAddress
        addressLine1: addressLine1
        mainAddressLine: mainAddressLine
        addressLine2: addressLine2
        addressLine3: addressLine3
        objectId: objectId
        addressLastLine: addressLastLine
        longitude: longitude
        unitValue: unitValue
        stateProvince: stateProvince
        urbanizationName: urbanizationName
        areaName1: areaName1
        areaName2: areaName2
        areaName3: areaName3
        areaName4: areaName4
        addressNumber: addressNumber
        postCode: postCode
        postCodeExt: postCodeExt
        placeName: placeName
        status: status
      properties:
        objectId:
          type: string
        displayName:
          type: string
        streetSide:
          type: string
        businessName:
          type: string
        addressLine1:
          type: string
        addressLine2:
          type: string
        addressLine3:
          type: string
        city:
          type: string
        stateProvince:
          type: string
        county:
          type: string
        postalCode:
          type: string
        latitude:
          type: string
        longitude:
          type: string
        status:
          type: string
        urbanizationName:
          type: string
        formattedAddress:
          type: string
        mainAddressLine:
          type: string
        addressLastLine:
          type: string
        placeName:
          type: string
        areaName1:
          type: string
        areaName2:
          type: string
        areaName3:
          type: string
        areaName4:
          type: string
        postCode:
          type: string
        postCodeExt:
          type: string
        country:
          type: string
        addressNumber:
          type: string
        streetName:
          type: string
        unitType:
          type: string
        unitValue:
          type: string
      type: object
    ErrorCode:
      properties:
        errorCode:
          type: string
        errorDescription:
          type: string
      type: object
  securitySchemes:
    oAuth2Password:
      flows:
        implicit:
          authorizationUrl: https://api.precisely.com/oauth/token
          scopes:
            bearer token: put your bearer token here.
      type: oauth2
externalDocs:
  description: Online Documentation
  url: https://docs.precisely.com/docs/sftw/precisely-apis/main/en-us/webhelp/apis/index.html
