openapi: 3.0.1
info:
  contact:
    name: Precisely APIs Support
    url: https://support.precisely.com
  description: '

    Demographics. Audience Enrichment. Add local demographics and lifestyle

    segmentation to your audience profiles. The Demographics API returns

    household demographics and lifestyle characteristics with the input of an

    address, location coordinate, or geographic boundary. This service covers

    select countries.'
  license:
    name: Apache 2.0
    url: http://springdoc.org
  termsOfService: http://swagger.io/terms/
  title: Precisely APIs Phone  Verification  Service API
  version: 18.1.0
servers:
- url: https://api.precisely.com
security:
- oAuth2Password:
  - ''
tags:
- name: Phone  Verification  Service
paths:
  /phoneverification/v2/validatephonenumber/results.json:
    post:
      description: This service accepts a phone number as input and returns details distinguishing landline and wireless numbers.
      operationId: validatephonenumber
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidatePhoneNumberAPIRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PhoneVerification'
            application/xml:
              schema:
                $ref: '#/components/schemas/PhoneVerification'
          description: successful operation
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorInfo'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorInfo'
          description: Bad Request
        '500':
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
          description: Internal Server Error
      security:
      - oAuth2Password: []
      summary: Phone verification.
      tags:
      - Phone  Verification  Service
      x-contentType: application/json
      x-accepts: application/json
components:
  schemas:
    ValidatePhoneNumberAPIRequest_Input_Row:
      example:
        PhoneNumber: PhoneNumber
        Country: Country
      properties:
        PhoneNumber:
          type: string
        Country:
          type: string
      type: object
    PhoneVerification_Output:
      example:
        CarrierName: CarrierName
        MNC: MNC
        user_fields:
        - user_fields
        - user_fields
        PhoneType: PhoneType
        PhoneNumberFormatted: PhoneNumberFormatted
        PhoneNumber: PhoneNumber
        MCC: MCC
        CountryCode: CountryCode
        ResultCode: ResultCode
      properties:
        MNC:
          type: string
        MCC:
          type: string
        CarrierName:
          type: string
        PhoneType:
          type: string
        PhoneNumberFormatted:
          type: string
        CountryCode:
          type: string
        PhoneNumber:
          type: string
        ResultCode:
          type: string
        user_fields:
          items:
            type: string
          type: array
      type: object
    ValidatePhoneNumberAPIRequest_Input:
      example:
        Row:
        - PhoneNumber: PhoneNumber
          Country: Country
        - PhoneNumber: PhoneNumber
          Country: Country
      properties:
        Row:
          items:
            $ref: '#/components/schemas/ValidatePhoneNumberAPIRequest_Input_Row'
          type: array
      type: object
    PhoneVerification:
      example:
        Output:
        - CarrierName: CarrierName
          MNC: MNC
          user_fields:
          - user_fields
          - user_fields
          PhoneType: PhoneType
          PhoneNumberFormatted: PhoneNumberFormatted
          PhoneNumber: PhoneNumber
          MCC: MCC
          CountryCode: CountryCode
          ResultCode: ResultCode
        - CarrierName: CarrierName
          MNC: MNC
          user_fields:
          - user_fields
          - user_fields
          PhoneType: PhoneType
          PhoneNumberFormatted: PhoneNumberFormatted
          PhoneNumber: PhoneNumber
          MCC: MCC
          CountryCode: CountryCode
          ResultCode: ResultCode
      properties:
        Output:
          items:
            $ref: '#/components/schemas/PhoneVerification_Output'
          type: array
      type: object
    ErrorInfo:
      properties:
        errors:
          items:
            $ref: '#/components/schemas/ErrorCode'
          type: array
          xml:
            name: error
      type: object
      xml:
        name: errors
    ValidatePhoneNumberAPIRequest:
      example:
        Input:
          Row:
          - PhoneNumber: PhoneNumber
            Country: Country
          - PhoneNumber: PhoneNumber
            Country: Country
      properties:
        Input:
          $ref: '#/components/schemas/ValidatePhoneNumberAPIRequest_Input'
      type: object
    ErrorCode:
      properties:
        errorCode:
          type: string
        errorDescription:
          type: string
      type: object
  securitySchemes:
    oAuth2Password:
      flows:
        implicit:
          authorizationUrl: https://api.precisely.com/oauth/token
          scopes:
            bearer token: put your bearer token here.
      type: oauth2
externalDocs:
  description: Online Documentation
  url: https://docs.precisely.com/docs/sftw/precisely-apis/main/en-us/webhelp/apis/index.html
